version: '3.7'
services:
  database: 
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=todo
  # todo_api:
  #   build:
  #     context: .
  #   environment:
  #     - DATABASE_URL=postgres://root:root@postgres:5432/todo
  #     - PORT=8080
  #   depends_on:
  #     - database
  #   ports:
  #     - 8080:8080
  proxy:
    image: nginx:latest
    restart: unless-stopped
    ports:
      - "1996:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
