version: '3.8'
services:
  database: 
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=todo
  todo_api:
    build:
      context: .
    environment:
      - DATABASE_URL=postgres://root:root@database:5432/todo
      - PORT=8080
      - NODE_ENV=production
    depends_on:
      - database
  proxy:
    image: nginx:latest
    restart: unless-stopped
    depends_on: 
      - todo_api
    ports:
      - "1996:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
